from time import sleep
print("    ** ** ** ** ** **")
sleep(1)
print("    || || || || || ||")
sleep(1)
print("^^^^^^&&&&&&&&&&&&^^^^^^")
print(" ")
print("H" , end="")
sleep(1)
print("a" , end="")
sleep(1)
print("p" , end="")
sleep(1)
print("p" , end="")
sleep(1)
print("y" , end="")
sleep(1)
print(" " , end="")
sleep(1)
print("B" , end="")
sleep(1)
print("i" , end="")
sleep(1)
print("r" , end="")
sleep(1)
print("t" , end="")
sleep(1)
print("h" , end="")
sleep(1)
print("d" , end="")
sleep(1)
print("a" , end="")
sleep(1)
print("y" , end="")
sleep(1)
print(" " , end="")
print("*kajal..." , end="")
sleep(1)
print(" ")
print("         .....\n         |||||\n        #######\n     @@@@@@@@@@@@@\n     @@@@@@ @@@@@@\n     @@@ KAJU @@@\n     @@@@@@ @@@@@@\n     @@@@@@@@@@@@@\n           &&\n         ******")
print("")
print("--------##############--------")
print(" (\_/)      (\_/)      (\_/)\n (*.*)      (*.*)      (*.*)\n(kaju)    (kaju)    (kaju)" )
sleep(1)
print("")
print("HAPPY BIRTHDAY kaju...!!\nwish you many many happy returns of the day.\nAnd i want to say few words for you that Hope ur special day brings u all that ur heart desires..!!\nHere's wishing u a day full of pleasant surprises..!!\nOn ur bday we wish for u that whatever u want most in life it comes to you just the way u imagined it or better..  \n *# MISS YOU DEAR..!!* ")
sleep(1)
print("*****************************")
print(" ")
sleep(1)
print("from: # { *AMOL...!!! }")
print("\n***************************")